apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-ns
  labels:
    app: javaweb-app
spec:
  containers:
  - name: cont-1
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javaweb-app
  ports:
    - port: 80          # Service port
      targetPort: 80   # Container port to forward traffic to
