apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  namespace: test-ns
spec: 
  replicas: 2
  template:
    metadata:
     name: my-rc-pod
     namespace: test-ns
    spec:
      containers:
      - name: cont-rc-2
        image: nginx
        ports:
        - containerPort: 80
